apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: squid
  labels:
    app: squid
spec:
  type: NodePort
  ports:
  - port: 3128
    nodePort: 31280
    name: http
  - port: 3129
    nodePort: 31290
    name: https
  selector:
    app: squid
